feat: TLS support for web (#301)
* Added TLS support for web

- Added optional configurations `cert_file` and `key_file` to run web server with https

Signed-off-by: Dmytro Bondar <git@bonddim.com>

* Helm chart update

- Refactored Ingress to use one host only (`config.web.external_url` is required)
- Added Certificate resource template (secret is mounted to container into `/app/certs/`)
- Added support for service with mixed protocols (exposes UI and Wireguard ports on same IP)
- Added helm-docs target to makefile
- Changed pod labels to use selectorLabels
- Removed default probes (app runs without healthy web)
- Removed sections from README

Signed-off-by: Dmytro Bondar <git@bonddim.com>

* Fix chart workflow path filter

* Fix chart lint issue

* Skip clean-up tested chart

* Try k3d cluster

---------

Signed-off-by: Dmytro Bondar <git@bonddim.com>

diff --git a/.github/workflows/chart.yml b/.github/workflows/chart.yml
--- a/.github/workflows/chart.yml
+++ b/.github/workflows/chart.yml
@@ -10,10 +10,10 @@ name: Chart
 on:
   pull_request:
     branches: [master]
-    paths: [deploy/helm]
+    paths: ['deploy/helm/**']
   push:
     branches: [master]
-    paths: [deploy/helm]
+    paths: ['deploy/helm/**']
 
 jobs:
   lint-test:
@@ -23,6 +23,14 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
+      - name: Check docs
+        run: |
+          make helm-docs
+          if ! git diff --exit-code; then
+            echo "error::Documentation is not up to date. Please run helm-docs and commit changes."
+            exit 1
+          fi
 
       # ct lint requires Python 3.x to run following packages:
       #  - yamale (https://github.com/23andMe/Yamale)
@@ -36,15 +44,9 @@ jobs:
       - name: Run chart-testing (lint)
         run: ct lint --config ct.yaml
 
-      - name: Check docs
-        run: |
-          docker run --rm --volume "${PWD}/deploy:/helm-docs" -u "$(id -u)" jnorwood/helm-docs
-          if ! git diff --exit-code; then
-            echo "error::Documentation is not up to date. Please run helm-docs and commit changes."
-            exit 1
-          fi
-
-      - uses: helm/kind-action@v1
+      - uses: nolar/setup-k3d-k3s@v1
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Run chart-testing (install)
         run: ct install --config ct.yaml
